name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install and Build
        # Replace 'YOUR_FOLDER_NAME' with the name of your subfolder (e.g., frontend)
        run: |
          cd YOUR_FOLDER_NAME
          npm install
          npm run build
        
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: YOUR_FIREBASE_PROJECT_ID  # Replace with your actual project ID
          channelId: live
